# f = open("this.py","r")
# # text = f.read()
# # text = f.readline()
# # text = f.readline()
# # text = f.readline()

# textList = f.readlines() 
# # print(text)
# print(textList)
# f.close()
f = open("this.txt","r")
text = f.read()
print(text)